# The folder where your nfts are, relative to this file.
NFT_DIR = "nfts"

# The wallet ID of the NFT wallet you create (see README)
WALLET_ID = 6

# Ardrive manifest file for your metadata
ARWEAVE_METADATA_MANIFEST_BASE_URL = "https://xxx.arweave.net/xxx/"

# Ardrive manifest file for your NFT images
ARWEAVE_NFT_MANIFEST_BASE_URL = "https://xxx.arweave.net/xxx/"


# Generate this yourself (see README)
COLLECTION_UUID = "GENERATE_ME"

# Locations on the net where your license can be found
LICENSE_URIS = [""]

# An address generated by the parent wallet of your NFT wallet
ROYALTY_ADDRESS = "xchaddresshere"

# An address generated by the parent wallet of your NFT wallet (can be the same as above, or different)
TARGET_ADDRESS = "xchaddresshere"

# Royalty expressed in % * 100 (i.e. 5% is 500)
ROYALTY_PERCENTAGE = 500

# Fee for minting your NFT RPC spendbundle (1000 mojos for now seems to be enough)
RPC_FEE = 1000
